### PR TITLE
Add automatic SQS processing using a lambda

### PR DESCRIPTION
**Pull request by eisnerw**
The project now has source for a new lambda that, through a mapping, can be invoked every time a message is queued on an SQS queue.  The original profile lambda now writes a time-stamped message to a queue and a new "messages" table has been added as a repository for the queued messages.  

When the original lambda is run prior to deploying and mapping the new lambda, the messages table remains empty.  After the new lambda has been deployed and mapped, each invocation of the profile lambda results in an automatic invocation of the SQS lambda when the profile lambda queues the time-stamped message.  These message can then be viewed in the new table.

### CODE REVIEW

**Comment by Blind-Striker** [comment]
Hi @eisnerw ,

Thanks again for your effort to make this example better. I ask you two things.

1-) We should create a .gitattributes file and add [profile-lambda-csharp/json](https://github.com/localstack-dotnet/localstack-serverless-dotnet-demo/blob/87522fbb24e911d1bb62a77d266616bdf6162af0/src/profile-lambda-csharp/json) file to there. Because right now %88 of this project seen as written in javascript.

2-) We need to update the architecture schema since you added an SQS and additional Lambda. You can use [Miro](https://miro.com/app/dashboard/) for drawing the new architecture and find new AWS icons in [here](https://aws.amazon.com/architecture/icons/). Alternatively, you can draw just a crude draft, and I can handle the rest.

(Looks like you can use draw.io too, AWS packed their new icons for draw.io. https://app.diagrams.net/?splash=0&libs=aws4)

Again thank you for your contribution.

**Comment by eisnerw** [comment]
> Hi @eisnerw ,
> 
> Thanks again for your effort to make this example better. I ask you two things.
> 
> 1-) We should create a .gitattributes file and add [profile-lambda-csharp/json](https://github.com/localstack-dotnet/localstack-serverless-dotnet-demo/blob/87522fbb24e911d1bb62a77d266616bdf6162af0/src/profile-lambda-csharp/json) file to there. Because right now %88 of this project seen as written in javascript.
> 
> 2-) We need to update the architecture schema since you added an SQS and additional Lambda. You can use [Miro](https://miro.com/app/dashboard/) for drawing the new architecture and find new AWS icons in [here](https://aws.amazon.com/architecture/icons/). Alternatively, you can draw just a crude draft, and I can handle the rest.
> 
> (Looks like you can use draw.io too, AWS packed their new icons for draw.io. https://app.diagrams.net/?splash=0&libs=aws4)
> 
> Again thank you for your contribution.

I've created a new diagram with Miro and added it to the project.  You can't see it within the readme until the PR is accepted.  There may be a problem with its sizing (from my commits, you'll see that I was using GitHub to add and re-add different versions).  I'm afraid that I don't understand the .gitattributes suggestion.

**Comment by Blind-Striker** [comment]
Thanks, @eisnerw much appreciated. I'll handle the .gitattributes issue

**Comment by Blind-Striker** [comment]
See the new .gitattributes file

https://github.com/localstack-dotnet/localstack-serverless-dotnet-demo/blob/master/.gitattributes

Before .gitattributes file, this project was seen as a javascript project on the repository's language stats. @eisnerw

**Comment by eisnerw** [comment]
> See the new .gitattributes file
> 
> https://github.com/localstack-dotnet/localstack-serverless-dotnet-demo/blob/master/.gitattributes
> 
> Before .gitattributes file, this project was seen as a javascript project on the repository's language stats. @eisnerw

@Blind-Striker, I can't say that I understand how github categorizes projects, but thanks for updating the .gitattributes file

**Pull request merged**
